### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by strengthnotes** [theflakes/ELSA#1]
Sorry wasn't sure where to ask this but can you comment on the DRC::Large_Outgoing_TX in your searches?

**Comment by theflakes** [comment]
Thanks, I removed those two lines.  They were looking in ELSA for what this Bro script would alert on:  https://github.com/theflakes/bro-scripts/blob/master/2.4-scripts/largeUpload.bro.

This Python ELSA correlation script needs more work and more complex correlation that includes weeding out of false positives on a per query basis..  Haven't had the chance to get back to it yet.

**Comment by strengthnotes** [comment]
Thanks for getting back to me so quick.

What do you think about running batch "reporting/hunting" at night similar to what you did here with more queries over things I might find interesting?  Has this correlation script proved effective?  Has ELSA had any problems with load?

**Comment by theflakes** [comment]
No problems with load for me so far.  Try scheduling it in a cron and go
from there.  If you implement smarter correlation than the simple
correlation I have please fork this script and submit a pull if you can.

With almost any hunting method there are almost always more misses than
hits.  Its a matter of constant tuning.  You'll find certain IPs that are
false positives that you will need to filter out.

**Comment by strengthnotes** [comment]
Great thanks.   If I get anything worthwhile done will submit a PR but my coding skills may not be up to par so we will see.
